[options]
; Password maestro para crear/borrar bases de datos desde la UI
admin_passwd = admin_token_senior

; Configuración de Base de Datos (nombres coinciden con docker-compose)
db_host = db
db_user = odoo
db_password = OdooyvtPa4f
db_port = 5432

; Path de Addons: El primero es el core de Odoo, el segundo es nuestra carpeta mapeada
addons_path = /mnt/extra-addons

; Log level para debuggear mejor
log_level = info